# --- DATABASE CONFIGURATION ---
# Changed 'postgres' to 'hospital' at the end of the URL
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalManagement
spring.datasource.username=postgres
spring.datasource.password=postgres-1
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE CONFIGURATION ---
# This ensures Hibernate speaks the correct PostgreSQL "dialect"
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# --- LOGGING ---
logging.level.root=INFO
# Useful to see if there are connection issues
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# --- THYMELEAF ---
spring.thymeleaf.cache=false

# --- MISC ---
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true